# -*- coding: utf-8 -*-
"""Sentinel-2 Cloud Masking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tk3nDEyirt5gvlWhLNX2J9it8b3BpM7
"""

import ee
import geemap
import xarray as xr
!pip install xee
import xee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

map = geemap.Map(basemap = 'SATELLITE')
map

roi = map.draw_last_feature.geometry()

roi

def cloud_mask(img):
  qa = img.select('probability')
  cloud_mask = qa.lt(20)
  ms = img.select('B.*').multiply(0.0001)
  ndvi = ms.normalizedDifference(['B8', 'B4']).rename('ndvi')
  return ndvi.updateMask(cloud_mask).copyProperties(img, ['system:time_start'])

sen2 = (
    ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED").linkCollection(
        ee.ImageCollection("COPERNICUS/S2_CLOUD_PROBABILITY"), 'probability'
    )
    .filterDate('2024','2025')
    .filterBounds(roi)
    .map(cloud_mask)
)

sen2

ds = xr.open_dataset(
    sen2,
    engine = 'ee',
    crs = 'EPSG:4326',
    geometry = roi,
    scale = 0.0003
)

ds

ds = ds.sortby('time') * 1

ds_weekly = ds.resample(time = 'W').max('time')

ds_weekly.ndvi.plot(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 8,
    robust = True
)

ds_rol = ds_weekly.rolling(time = 15, min_periods = 1, center = True).mean('time')

ds_rol.ndvi.plot(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 8,
    robust = True
)